Add verification of Homebrew formula installation
build-trust/homebrew-ockam pull request #42
Opened 2022-10-21 18:09 UTC by memark

Verify installation of homebrew formula on MacOS 12 and Ubuntu 22.04, both on Intel.

MacOS on ARM (M1) is supported by Homebrew, but not by Github runners (we would need self-hosting).

Linux on ARM is not supported by Homebrew. (I tried getting it to work, but didn't succeed.)

Resolves https://github.com/build-trust/ockam/issues/3696

2022-10-22 06:30 UTC, mrinalwadhwa requested changes
That's looks great! Thank you.
Left a couple of small suggestions.

2022-10-22 06:30 UTC, mrinalwadhwa commented on .github/workflows/verify-pull-request.yml
> +  pull_request
Let's change this to.
The explicit read permission is good safety measure.
Workflow dispatch and push triggers are useful in our workflows so we use them across almost all actions.

https://github.com/build-trust/ockam/blob/31a4d1d95d1c482f70f2c10d2c80715d54289223/.github/workflows/commits.yml#L3-L6

2022-10-22 06:30 UTC, mrinalwadhwa commented on .github/workflows/verify-pull-request.yml
> +      - uses: actions/checkout@v3
We try to pin our dependencies, please change to: 

```suggestion
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
```

2022-10-22 06:30 UTC, mrinalwadhwa commented on .github/workflows/verify-pull-request.yml
> +      - uses: actions/checkout@v3
We try to pin our dependencies, please change to: 

```suggestion
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
```

2022-10-22 06:36 UTC, mrinalwadhwa commented
Added a new issue to add dependabot to this repo so we can keep the pinned hashes up to date
https://github.com/build-trust/ockam/issues/3712

2022-10-22 18:19 UTC, memark commented on .github/workflows/verify-pull-request.yml
> +  pull_request
Good thing with explicit permissions. Was not aware they even existed!

2022-10-23 04:19 UTC, mrinalwadhwa approved these changes

2022-10-23 04:19 UTC, mrinalwadhwa commented
Thank you for another awesome contribution! 🥳

2022-10-23 04:21 UTC, merged